[profile.default]
auto_detect_solc = true
src = "src"
out = "out"
libs = ["lib"]
ffi = true  # for running foundry-huff
# solc = "0.8.20"  # uncomment to specify the solc version to use slither on single file

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
fs_permissions = [{ access = "read", path = "./broadcast" }]